<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Afrixis</title>
    <link rel="shortcut icon" type="image/icn" href="<?php echo base_url('assets/images/title.png')?>"/>
</head>
<body>
<div style="font-size: 20px; padding:50px">
    <a href="<?php echo base_url().'user/login';?>" style="float: right; font-size: 30px">Return</a>
    <b style="font-size: 50px;">Privacy Policy</b><br>
    <pre>Effective date: October 19, 2019<br></pre>
    Afrixis International Limited ("us", "we", or "our") operates the www.afrixis.com website (hereinafter referred to as the "Service").<br>
    This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.<br>
    We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from www.afrixis.com<br><br>
    <b style="font-size:20px; color:dodgerblue">Definitions</b><br>
    <p>Service<br>
        Service is the www.afrixis.com website operated by afrixis International Limited<br>
        Personal Data<br>
        Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).<br>
        Usage Data<br>
        Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).<br>
        Cookies<br>
        Cookies are small files stored on your device (computer or mobile device).<br>
        Data Controller<br>
        Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.<br>
        For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.<br>
        Data Processors (or Service Providers)<br>
        Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.<br>
        We may use the services of various Service Providers in order to process your data more effectively.<br>
        Data Subject (or User)<br>
        Data Subject is any living individual who is using our Service and is the subject of Personal Data.</p><br>
    <b style="font-size:20px; color:dodgerblue">Information Collection and Use</b><br>
    We collect several different types of information for various purposes to provide and improve our Service to you.<br>
    <b style="font-size:20px; color:dodgerblue">Types of Data Collected</b><br>
    <b style="font-size:20px; color:dodgerblue">Personal Data</b><br>
    While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:<br>
    •	Email address<br>
    •	Cookies and Usage Data<br>
    We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or the instructions provided in any email we send.<br>
    <b style="font-size:20px; color:dodgerblue">Usage Data</b><br>
    We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.<br>
    <b style="font-size:20px; color:dodgerblue">Tracking Cookies Data</b><br>
    We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.<br>
    Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.<br>
    You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.<br>
    Examples of Cookies we use:<br>
    •	Session Cookies. We use Session Cookies to operate our Service.<br>
    •	Preference Cookies. We use Preference Cookies to remember your preferences and various settings.<br>
    •	Security Cookies. We use Security Cookies for security purposes.<br>
    <b style="font-size:20px; color:dodgerblue">Use of Data</b><br>
    afrixis International Limited uses the collected data for various purposes:<br>
    •	To provide and maintain our Service<br>
    •	To notify you about changes to our Service<br>
    •	To allow you to participate in interactive features of our Service when you choose to do so<br>
    •	To provide customer support<br>
    •	To gather analysis or valuable information so that we can improve our Service<br>
    •	To monitor the usage of our Service<br>
    •	To detect, prevent and address technical issues<br>
    •	To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information<br>
    <b style="font-size:20px; color:dodgerblue">Legal Basis for Processing Personal Data under the General Data Protection Regulation (GDPR)</b><br>
    If you are from the European Economic Area (EEA), afrixis International Limited legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.<br>
    afrixis International Limited may process your Personal Data because:<br>
    •	We need to perform a contract with you<br>
    •	You have given us permission to do so<br>
    •	The processing is in our legitimate interests and it is not overridden by your rights<br>
    •	To comply with the law<br>
    <b style="font-size:20px; color:dodgerblue">Retention of Data</b><br>
    afrixis International Limited will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes and enforce our legal agreements and policies.<br>
    afrixis International Limited will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.<br>
    <b style="font-size:20px; color:dodgerblue">Transfer of Data</b><br>
    Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.<br>
    If you are located outside United Kingdom and choose to provide information to us, please note that we transfer the data, including Personal Data, to United Kingdom and process it there.<br>
    Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.<br>
    afrixis International Limited will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.<br>
    <b style="font-size:20px; color:dodgerblue">Disclosure of Data</b><br>
    <b style="font-size:20px; color:dodgerblue">Legal Requirements</b><br>
    afrixis International Limited may disclose your Personal Data in the good faith belief that such action is necessary to:<br>
    •	To comply with a legal obligation<br>
    •	To protect and defend the rights or property of afrixis International Limited<br>
    •	To prevent or investigate possible wrongdoing in connection with the Service<br>
    •	To protect the personal safety of users of the Service or the public<br>
    •	To protect against legal liability<br>
    <b style="font-size:20px; color:dodgerblue">Security of Data</b><br>
    The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.<br>
    <b style="font-size:20px; color:dodgerblue">Your Data Protection Rights under the General Data Protection Regulation (GDPR)</b><br>
    If you are a resident of the European Economic Area (EEA), you have certain data protection rights. afrixis International Limited aims to take reasonable steps to allow you to correct, amend, delete or limit the use of your Personal Data.<br>
    If you wish to be informed about what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.<br>
    In certain circumstances, you have the following data protection rights:<br>
    <p>The right to access, update or delete the information we have on you. Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.<br>
        The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.<br>
        The right to object. You have the right to object to our processing of your Personal Data.<br>
        The right of restriction. You have the right to request that we restrict the processing of your personal information.<br>
        The right to data portability. You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.<br>
        The right to withdraw consent. You also have the right to withdraw your consent at any time where afrixis International Limited relied on your consent to process your personal information.</p><br>
    Please note that we may ask you to verify your identity before responding to such requests.<br>
    You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).<br>
    <b style="font-size:20px; color:dodgerblue">Service Providers</b><br>
    We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.<br>
    These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.<br>
    <b style="font-size:20px; color:dodgerblue">Analytics</b><br>
    We may use third-party Service Providers to monitor and analyse the use of our Service.<br>
    <b style="font-size:20px; color:dodgerblue">Contact Us</b><br>
    If you have any questions about this Privacy Policy, please contact us:<br>
    •	By email: help@afrixis.com<br>

</div>
</body>
</html>
